// Core
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faUserAstronaut,
    faArrowRight,
    faRedo,
    faLongArrowAltRight,
    faTimesCircle,
    faPlus,
    faWrench,
    faTrashAlt,
    faReply,
    faShare,
    faCalendarAlt,
    faMask,
    faUtensils,
    faTable,
    faSave,
    faCompass,
    faTimes,
    faCheckCircle,
    faEye,
    faEyeSlash,
    faCog,
    faCheck,
} from '@fortawesome/free-solid-svg-icons';

export const initIconsLibrary = () => library.add(
    faUserAstronaut,
    faArrowRight,
    faRedo,
    faLongArrowAltRight,
    faTimesCircle,
    faPlus,
    faWrench,
    faTrashAlt,
    faReply,
    faShare,
    faCalendarAlt,
    faMask,
    faUtensils,
    faTable,
    faSave,
    faCompass,
    faTimes,
    faCheckCircle,
    faEye,
    faEyeSlash,
    faCog,
    faCheck,
);
